spring:
  application:
    name: qiyu-live-id-generate-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.13:8808/giyu_live_common?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
dubbo:
  application:
    name: qiyu-live-id-generate-provider
  registry:
    address: nacos://192.168.1.13:8848?namespace=02fefda0-eab7-4294-88d9-fce90266b07a
    use-as-config-center: false
    use-as-metadata-center: false
  protocol:
    name: dubbo
    port: 9098