#spring:
#  application:
#    name: qiyu-live-user-provider
#  datasource:
#    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:qiyu-db-sharding.yaml
#    username: root
#    password: root
#    hikari:
#      pool-name: qiyu-user-pool
#      minimum-idle: 150
#      maximum-pool-size: 300
#      #      connection-init-sql: select 1
#      connection-timeout: 4000
#      max-lifetime: 60000
#  data:
#    redis:
#      port: 6379
#      host: 192.168.1.13
#      password: 123456
#      lettuce:
#        pool:
#          min-idle: 10
#          max-idle: 20
#          max-active: 50
#
##rocketmq的配置
#qiyu:
#  rmq:
#    producer:
#      name-srv: 192.168.1.13:9876
#      group-name: ${spring.application.name}
#      retry-times: 3
#      send-time-out: 3000
#    consumer:
#      name-srv: 192.168.1.13:9876
#      group-name: ${spring.application.name}
#
#
## Dubbo配置
#dubbo:
#  application:
#    name: qiyu-live-user-provider
#  registry:
#    address: nacos://192.168.1.13:8848?namespace=02fefda0-eab7-4294-88d9-fce90266b07a
#    use-as-config-center: false
#    use-as-metadata-center: false
#  protocol:
#    name: dubbo
#    port: 9091
